export const CLEAR_SUGGESTIONS = 'qgo/search/CLEAR_SUGGESTIONS';

export const STORE_SUGGESTIONS = 'qgo/search/STORE_SUGGESTIONS';

export const RETRIEVE_SUGGESTIONS = 'qgo/search/RETRIEVE_SUGGESTIONS';

export const RETRIEVE_SEARCH_RESULTS = 'qgo/search/RETRIEVE_SEARCH_RESULTS';
